//this source code was auto-generated by tolua#, do not modify it
using System;
using System.Collections.Generic;
using LuaInterface;

public static class DelegateFactory
{
	public delegate Delegate DelegateValue(LuaFunction func, LuaTable self, bool flag);
	public static Dictionary<Type, DelegateValue> dict = new Dictionary<Type, DelegateValue>();

	static DelegateFactory()
	{
		Register();
	}

	[NoToLuaAttribute]
	public static void Register()
	{
		dict.Clear();
		dict.Add(typeof(System.Action), System_Action);
		dict.Add(typeof(UnityEngine.Events.UnityAction), UnityEngine_Events_UnityAction);
		dict.Add(typeof(System.Predicate<int>), System_Predicate_int);
		dict.Add(typeof(System.Action<int>), System_Action_int);
		dict.Add(typeof(System.Comparison<int>), System_Comparison_int);
		dict.Add(typeof(UnityEngine.Camera.CameraCallback), UnityEngine_Camera_CameraCallback);
		dict.Add(typeof(UnityEngine.Application.LowMemoryCallback), UnityEngine_Application_LowMemoryCallback);
		dict.Add(typeof(UnityEngine.Application.AdvertisingIdentifierCallback), UnityEngine_Application_AdvertisingIdentifierCallback);
		dict.Add(typeof(UnityEngine.Application.LogCallback), UnityEngine_Application_LogCallback);
		dict.Add(typeof(UnityEngine.AudioClip.PCMReaderCallback), UnityEngine_AudioClip_PCMReaderCallback);
		dict.Add(typeof(UnityEngine.AudioClip.PCMSetPositionCallback), UnityEngine_AudioClip_PCMSetPositionCallback);
		dict.Add(typeof(UnityEngine.Canvas.WillRenderCanvases), UnityEngine_Canvas_WillRenderCanvases);
		dict.Add(typeof(UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode>), UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode);
		dict.Add(typeof(UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene>), UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene);
		dict.Add(typeof(UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene>), UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene);
		dict.Add(typeof(UnityEngine.RectTransform.ReapplyDrivenProperties), UnityEngine_RectTransform_ReapplyDrivenProperties);
		dict.Add(typeof(UnityEngine.UI.InputField.OnValidateInput), UnityEngine_UI_InputField_OnValidateInput);
		dict.Add(typeof(System.Threading.ThreadStart), System_Threading_ThreadStart);
		dict.Add(typeof(System.Action<UnityEngine.Transform>), System_Action_UnityEngine_Transform);
		dict.Add(typeof(System.Action<NotiData>), System_Action_NotiData);
		dict.Add(typeof(System.Action<UnityEngine.Object[]>), System_Action_UnityEngine_Objects);
		dict.Add(typeof(System.Action<int,int>), System_Action_int_int);
		dict.Add(typeof(System.Action<UnityEngine.GameObject>), System_Action_UnityEngine_GameObject);
		dict.Add(typeof(System.Action<UnityEngine.EventSystems.PointerEventData>), System_Action_UnityEngine_EventSystems_PointerEventData);
		dict.Add(typeof(System.Action<object>), System_Action_object);
		dict.Add(typeof(System.Action<UIScrollWrap,int>), System_Action_UIScrollWrap_int);
		dict.Add(typeof(System.Action<UIScrollWrap>), System_Action_UIScrollWrap);
		dict.Add(typeof(System.Action<Handle.WndType,object>), System_Action_Handle_WndType_object);
		dict.Add(typeof(System.Func<Handle,float>), System_Func_Handle_float);
		dict.Add(typeof(System.Func<Handle,int>), System_Func_Handle_int);
		dict.Add(typeof(System.Func<Handle,UnityEngine.Vector3>), System_Func_Handle_UnityEngine_Vector3);
		dict.Add(typeof(System.Func<Handle,UnityEngine.Color>), System_Func_Handle_UnityEngine_Color);
		dict.Add(typeof(System.Func<bool>), System_Func_bool);
		dict.Add(typeof(System.Action<StateGroup,int>), System_Action_StateGroup_int);
		dict.Add(typeof(System.Action<StateHandle,int>), System_Action_StateHandle_int);
		dict.Add(typeof(System.Action<Handle>), System_Action_Handle);
		dict.Add(typeof(System.Action<StateHandle>), System_Action_StateHandle);
		dict.Add(typeof(System.Action<LuaInterface.LuaTable>), System_Action_LuaInterface_LuaTable);
		dict.Add(typeof(System.Action<LuaInterface.LuaTable,StateHandle>), System_Action_LuaInterface_LuaTable_StateHandle);
		dict.Add(typeof(System.Action<LuaInterface.LuaTable,StateHandle,int>), System_Action_LuaInterface_LuaTable_StateHandle_int);
		dict.Add(typeof(System.Action<LuaInterface.LuaTable,UnityEngine.EventSystems.PointerEventData>), System_Action_LuaInterface_LuaTable_UnityEngine_EventSystems_PointerEventData);
		dict.Add(typeof(CenterOnChild.OnCenterHandler), CenterOnChild_OnCenterHandler);
	}

    [NoToLuaAttribute]
    public static Delegate CreateDelegate(Type t, LuaFunction func = null)
    {
        DelegateValue Create = null;

        if (!dict.TryGetValue(t, out Create))
        {
            throw new LuaException(string.Format("Delegate {0} not register", LuaMisc.GetTypeName(t)));            
        }

        if (func != null)
        {
            LuaState state = func.GetLuaState();
            LuaDelegate target = state.GetLuaDelegate(func);
            
            if (target != null)
            {
                return Delegate.CreateDelegate(t, target, target.method);
            }  
            else
            {
                Delegate d = Create(func, null, false);
                target = d.Target as LuaDelegate;
                state.AddLuaDelegate(target, func);
                return d;
            }       
        }

        return Create(func, null, false);        
    }

    [NoToLuaAttribute]
    public static Delegate CreateDelegate(Type t, LuaFunction func, LuaTable self)
    {
        DelegateValue Create = null;

        if (!dict.TryGetValue(t, out Create))
        {
            throw new LuaException(string.Format("Delegate {0} not register", LuaMisc.GetTypeName(t)));
        }

        if (func != null)
        {
            LuaState state = func.GetLuaState();
            LuaDelegate target = state.GetLuaDelegate(func, self);

            if (target != null)
            {
                return Delegate.CreateDelegate(t, target, target.method);
            }
            else
            {
                Delegate d = Create(func, self, true);
                target = d.Target as LuaDelegate;
                state.AddLuaDelegate(target, func, self);
                return d;
            }
        }

        return Create(func, self, true);
    }

    [NoToLuaAttribute]
    public static Delegate RemoveDelegate(Delegate obj, LuaFunction func)
    {
        LuaState state = func.GetLuaState();
        Delegate[] ds = obj.GetInvocationList();

        for (int i = 0; i < ds.Length; i++)
        {
            LuaDelegate ld = ds[i].Target as LuaDelegate;

            if (ld != null && ld.func == func)
            {
                obj = Delegate.Remove(obj, ds[i]);
                state.DelayDispose(ld.func);
                break;
            }
        }

        return obj;
    }

    [NoToLuaAttribute]
    public static Delegate RemoveDelegate(Delegate obj, Delegate dg)
    {
        LuaDelegate remove = dg.Target as LuaDelegate;

        if (remove == null)
        {
            obj = Delegate.Remove(obj, dg);
            return obj;
        }

        LuaState state = remove.func.GetLuaState();
        Delegate[] ds = obj.GetInvocationList();        

        for (int i = 0; i < ds.Length; i++)
        {
            LuaDelegate ld = ds[i].Target as LuaDelegate;

            if (ld != null && ld == remove)
            {
                obj = Delegate.Remove(obj, ds[i]);
                state.DelayDispose(ld.func);
                state.DelayDispose(ld.self);
                break;
            }
        }

        return obj;
    }

	class System_Action_Event : LuaDelegate
	{
		public System_Action_Event(LuaFunction func) : base(func) { }
		public System_Action_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			System_Action_Event target = new System_Action_Event(func);
			System.Action d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_Event target = new System_Action_Event(func, self);
			System.Action d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Events_UnityAction_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_Event target = new UnityEngine_Events_UnityAction_Event(func);
			UnityEngine.Events.UnityAction d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_Event target = new UnityEngine_Events_UnityAction_Event(func, self);
			UnityEngine.Events.UnityAction d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Predicate_int_Event : LuaDelegate
	{
		public System_Predicate_int_Event(LuaFunction func) : base(func) { }
		public System_Predicate_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public bool Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}

		public bool CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Predicate_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Predicate<int> fn = delegate(int param0) { return false; };
			return fn;
		}

		if(!flag)
		{
			System_Predicate_int_Event target = new System_Predicate_int_Event(func);
			System.Predicate<int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Predicate_int_Event target = new System_Predicate_int_Event(func, self);
			System.Predicate<int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_int_Event : LuaDelegate
	{
		public System_Action_int_Event(LuaFunction func) : base(func) { }
		public System_Action_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<int> fn = delegate(int param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_int_Event target = new System_Action_int_Event(func);
			System.Action<int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_int_Event target = new System_Action_int_Event(func, self);
			System.Action<int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Comparison_int_Event : LuaDelegate
	{
		public System_Comparison_int_Event(LuaFunction func) : base(func) { }
		public System_Comparison_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public int Call(int param0, int param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}

		public int CallWithSelf(int param0, int param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Comparison_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Comparison<int> fn = delegate(int param0, int param1) { return 0; };
			return fn;
		}

		if(!flag)
		{
			System_Comparison_int_Event target = new System_Comparison_int_Event(func);
			System.Comparison<int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Comparison_int_Event target = new System_Comparison_int_Event(func, self);
			System.Comparison<int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Camera_CameraCallback_Event : LuaDelegate
	{
		public UnityEngine_Camera_CameraCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Camera_CameraCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.Camera param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.Camera param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Camera_CameraCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Camera.CameraCallback fn = delegate(UnityEngine.Camera param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Camera_CameraCallback_Event target = new UnityEngine_Camera_CameraCallback_Event(func);
			UnityEngine.Camera.CameraCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Camera_CameraCallback_Event target = new UnityEngine_Camera_CameraCallback_Event(func, self);
			UnityEngine.Camera.CameraCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Application_LowMemoryCallback_Event : LuaDelegate
	{
		public UnityEngine_Application_LowMemoryCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Application_LowMemoryCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Application_LowMemoryCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Application.LowMemoryCallback fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Application_LowMemoryCallback_Event target = new UnityEngine_Application_LowMemoryCallback_Event(func);
			UnityEngine.Application.LowMemoryCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Application_LowMemoryCallback_Event target = new UnityEngine_Application_LowMemoryCallback_Event(func, self);
			UnityEngine.Application.LowMemoryCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Application_AdvertisingIdentifierCallback_Event : LuaDelegate
	{
		public UnityEngine_Application_AdvertisingIdentifierCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Application_AdvertisingIdentifierCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0, bool param1, string param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0, bool param1, string param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Application_AdvertisingIdentifierCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Application.AdvertisingIdentifierCallback fn = delegate(string param0, bool param1, string param2) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Application_AdvertisingIdentifierCallback_Event target = new UnityEngine_Application_AdvertisingIdentifierCallback_Event(func);
			UnityEngine.Application.AdvertisingIdentifierCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Application_AdvertisingIdentifierCallback_Event target = new UnityEngine_Application_AdvertisingIdentifierCallback_Event(func, self);
			UnityEngine.Application.AdvertisingIdentifierCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Application_LogCallback_Event : LuaDelegate
	{
		public UnityEngine_Application_LogCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Application_LogCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0, string param1, UnityEngine.LogType param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0, string param1, UnityEngine.LogType param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Application_LogCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Application.LogCallback fn = delegate(string param0, string param1, UnityEngine.LogType param2) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Application_LogCallback_Event target = new UnityEngine_Application_LogCallback_Event(func);
			UnityEngine.Application.LogCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Application_LogCallback_Event target = new UnityEngine_Application_LogCallback_Event(func, self);
			UnityEngine.Application.LogCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_AudioClip_PCMReaderCallback_Event : LuaDelegate
	{
		public UnityEngine_AudioClip_PCMReaderCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_AudioClip_PCMReaderCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(float[] param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(float[] param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_AudioClip_PCMReaderCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.AudioClip.PCMReaderCallback fn = delegate(float[] param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_AudioClip_PCMReaderCallback_Event target = new UnityEngine_AudioClip_PCMReaderCallback_Event(func);
			UnityEngine.AudioClip.PCMReaderCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_AudioClip_PCMReaderCallback_Event target = new UnityEngine_AudioClip_PCMReaderCallback_Event(func, self);
			UnityEngine.AudioClip.PCMReaderCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_AudioClip_PCMSetPositionCallback_Event : LuaDelegate
	{
		public UnityEngine_AudioClip_PCMSetPositionCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_AudioClip_PCMSetPositionCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_AudioClip_PCMSetPositionCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.AudioClip.PCMSetPositionCallback fn = delegate(int param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_AudioClip_PCMSetPositionCallback_Event target = new UnityEngine_AudioClip_PCMSetPositionCallback_Event(func);
			UnityEngine.AudioClip.PCMSetPositionCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_AudioClip_PCMSetPositionCallback_Event target = new UnityEngine_AudioClip_PCMSetPositionCallback_Event(func, self);
			UnityEngine.AudioClip.PCMSetPositionCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Canvas_WillRenderCanvases_Event : LuaDelegate
	{
		public UnityEngine_Canvas_WillRenderCanvases_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Canvas_WillRenderCanvases_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Canvas_WillRenderCanvases(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Canvas.WillRenderCanvases fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Canvas_WillRenderCanvases_Event target = new UnityEngine_Canvas_WillRenderCanvases_Event(func);
			UnityEngine.Canvas.WillRenderCanvases d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Canvas_WillRenderCanvases_Event target = new UnityEngine_Canvas_WillRenderCanvases_Event(func, self);
			UnityEngine.Canvas.WillRenderCanvases d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.LoadSceneMode param1)
		{
			func.BeginPCall();
			func.PushValue(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.LoadSceneMode param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushValue(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode> fn = delegate(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.LoadSceneMode param1) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event(func);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event(func, self);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.SceneManagement.Scene param0)
		{
			func.BeginPCall();
			func.PushValue(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.SceneManagement.Scene param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushValue(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene> fn = delegate(UnityEngine.SceneManagement.Scene param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event(func);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event(func, self);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.Scene param1)
		{
			func.BeginPCall();
			func.PushValue(param0);
			func.PushValue(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.Scene param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushValue(param0);
			func.PushValue(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene> fn = delegate(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.Scene param1) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event(func);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event(func, self);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_RectTransform_ReapplyDrivenProperties_Event : LuaDelegate
	{
		public UnityEngine_RectTransform_ReapplyDrivenProperties_Event(LuaFunction func) : base(func) { }
		public UnityEngine_RectTransform_ReapplyDrivenProperties_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.RectTransform param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.RectTransform param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_RectTransform_ReapplyDrivenProperties(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.RectTransform.ReapplyDrivenProperties fn = delegate(UnityEngine.RectTransform param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_RectTransform_ReapplyDrivenProperties_Event target = new UnityEngine_RectTransform_ReapplyDrivenProperties_Event(func);
			UnityEngine.RectTransform.ReapplyDrivenProperties d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_RectTransform_ReapplyDrivenProperties_Event target = new UnityEngine_RectTransform_ReapplyDrivenProperties_Event(func, self);
			UnityEngine.RectTransform.ReapplyDrivenProperties d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_UI_InputField_OnValidateInput_Event : LuaDelegate
	{
		public UnityEngine_UI_InputField_OnValidateInput_Event(LuaFunction func) : base(func) { }
		public UnityEngine_UI_InputField_OnValidateInput_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public char Call(string param0, int param1, char param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			char ret = (char)func.CheckNumber();
			func.EndPCall();
			return ret;
		}

		public char CallWithSelf(string param0, int param1, char param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			char ret = (char)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate UnityEngine_UI_InputField_OnValidateInput(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.UI.InputField.OnValidateInput fn = delegate(string param0, int param1, char param2) { return '\0'; };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_UI_InputField_OnValidateInput_Event target = new UnityEngine_UI_InputField_OnValidateInput_Event(func);
			UnityEngine.UI.InputField.OnValidateInput d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_UI_InputField_OnValidateInput_Event target = new UnityEngine_UI_InputField_OnValidateInput_Event(func, self);
			UnityEngine.UI.InputField.OnValidateInput d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Threading_ThreadStart_Event : LuaDelegate
	{
		public System_Threading_ThreadStart_Event(LuaFunction func) : base(func) { }
		public System_Threading_ThreadStart_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Threading_ThreadStart(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Threading.ThreadStart fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			System_Threading_ThreadStart_Event target = new System_Threading_ThreadStart_Event(func);
			System.Threading.ThreadStart d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Threading_ThreadStart_Event target = new System_Threading_ThreadStart_Event(func, self);
			System.Threading.ThreadStart d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_UnityEngine_Transform_Event : LuaDelegate
	{
		public System_Action_UnityEngine_Transform_Event(LuaFunction func) : base(func) { }
		public System_Action_UnityEngine_Transform_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.Transform param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.Transform param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_Transform(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<UnityEngine.Transform> fn = delegate(UnityEngine.Transform param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_UnityEngine_Transform_Event target = new System_Action_UnityEngine_Transform_Event(func);
			System.Action<UnityEngine.Transform> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_UnityEngine_Transform_Event target = new System_Action_UnityEngine_Transform_Event(func, self);
			System.Action<UnityEngine.Transform> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_NotiData_Event : LuaDelegate
	{
		public System_Action_NotiData_Event(LuaFunction func) : base(func) { }
		public System_Action_NotiData_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(NotiData param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(NotiData param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_NotiData(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<NotiData> fn = delegate(NotiData param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_NotiData_Event target = new System_Action_NotiData_Event(func);
			System.Action<NotiData> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_NotiData_Event target = new System_Action_NotiData_Event(func, self);
			System.Action<NotiData> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_UnityEngine_Objects_Event : LuaDelegate
	{
		public System_Action_UnityEngine_Objects_Event(LuaFunction func) : base(func) { }
		public System_Action_UnityEngine_Objects_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.Object[] param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.Object[] param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_Objects(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<UnityEngine.Object[]> fn = delegate(UnityEngine.Object[] param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_UnityEngine_Objects_Event target = new System_Action_UnityEngine_Objects_Event(func);
			System.Action<UnityEngine.Object[]> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_UnityEngine_Objects_Event target = new System_Action_UnityEngine_Objects_Event(func, self);
			System.Action<UnityEngine.Object[]> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_int_int_Event : LuaDelegate
	{
		public System_Action_int_int_Event(LuaFunction func) : base(func) { }
		public System_Action_int_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(int param0, int param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(int param0, int param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_int_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<int,int> fn = delegate(int param0, int param1) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_int_int_Event target = new System_Action_int_int_Event(func);
			System.Action<int,int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_int_int_Event target = new System_Action_int_int_Event(func, self);
			System.Action<int,int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_UnityEngine_GameObject_Event : LuaDelegate
	{
		public System_Action_UnityEngine_GameObject_Event(LuaFunction func) : base(func) { }
		public System_Action_UnityEngine_GameObject_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.GameObject param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.GameObject param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_GameObject(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<UnityEngine.GameObject> fn = delegate(UnityEngine.GameObject param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_UnityEngine_GameObject_Event target = new System_Action_UnityEngine_GameObject_Event(func);
			System.Action<UnityEngine.GameObject> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_UnityEngine_GameObject_Event target = new System_Action_UnityEngine_GameObject_Event(func, self);
			System.Action<UnityEngine.GameObject> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_UnityEngine_EventSystems_PointerEventData_Event : LuaDelegate
	{
		public System_Action_UnityEngine_EventSystems_PointerEventData_Event(LuaFunction func) : base(func) { }
		public System_Action_UnityEngine_EventSystems_PointerEventData_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.EventSystems.PointerEventData param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.EventSystems.PointerEventData param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_EventSystems_PointerEventData(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<UnityEngine.EventSystems.PointerEventData> fn = delegate(UnityEngine.EventSystems.PointerEventData param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_UnityEngine_EventSystems_PointerEventData_Event target = new System_Action_UnityEngine_EventSystems_PointerEventData_Event(func);
			System.Action<UnityEngine.EventSystems.PointerEventData> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_UnityEngine_EventSystems_PointerEventData_Event target = new System_Action_UnityEngine_EventSystems_PointerEventData_Event(func, self);
			System.Action<UnityEngine.EventSystems.PointerEventData> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_object_Event : LuaDelegate
	{
		public System_Action_object_Event(LuaFunction func) : base(func) { }
		public System_Action_object_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(object param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(object param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_object(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<object> fn = delegate(object param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_object_Event target = new System_Action_object_Event(func);
			System.Action<object> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_object_Event target = new System_Action_object_Event(func, self);
			System.Action<object> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_UIScrollWrap_int_Event : LuaDelegate
	{
		public System_Action_UIScrollWrap_int_Event(LuaFunction func) : base(func) { }
		public System_Action_UIScrollWrap_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UIScrollWrap param0, int param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UIScrollWrap param0, int param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UIScrollWrap_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<UIScrollWrap,int> fn = delegate(UIScrollWrap param0, int param1) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_UIScrollWrap_int_Event target = new System_Action_UIScrollWrap_int_Event(func);
			System.Action<UIScrollWrap,int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_UIScrollWrap_int_Event target = new System_Action_UIScrollWrap_int_Event(func, self);
			System.Action<UIScrollWrap,int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_UIScrollWrap_Event : LuaDelegate
	{
		public System_Action_UIScrollWrap_Event(LuaFunction func) : base(func) { }
		public System_Action_UIScrollWrap_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UIScrollWrap param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UIScrollWrap param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UIScrollWrap(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<UIScrollWrap> fn = delegate(UIScrollWrap param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_UIScrollWrap_Event target = new System_Action_UIScrollWrap_Event(func);
			System.Action<UIScrollWrap> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_UIScrollWrap_Event target = new System_Action_UIScrollWrap_Event(func, self);
			System.Action<UIScrollWrap> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_Handle_WndType_object_Event : LuaDelegate
	{
		public System_Action_Handle_WndType_object_Event(LuaFunction func) : base(func) { }
		public System_Action_Handle_WndType_object_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(Handle.WndType param0, object param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(Handle.WndType param0, object param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_Handle_WndType_object(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<Handle.WndType,object> fn = delegate(Handle.WndType param0, object param1) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_Handle_WndType_object_Event target = new System_Action_Handle_WndType_object_Event(func);
			System.Action<Handle.WndType,object> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_Handle_WndType_object_Event target = new System_Action_Handle_WndType_object_Event(func, self);
			System.Action<Handle.WndType,object> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Func_Handle_float_Event : LuaDelegate
	{
		public System_Func_Handle_float_Event(LuaFunction func) : base(func) { }
		public System_Func_Handle_float_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public float Call(Handle param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			float ret = (float)func.CheckNumber();
			func.EndPCall();
			return ret;
		}

		public float CallWithSelf(Handle param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			float ret = (float)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Func_Handle_float(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Func<Handle,float> fn = delegate(Handle param0) { return 0; };
			return fn;
		}

		if(!flag)
		{
			System_Func_Handle_float_Event target = new System_Func_Handle_float_Event(func);
			System.Func<Handle,float> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Func_Handle_float_Event target = new System_Func_Handle_float_Event(func, self);
			System.Func<Handle,float> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Func_Handle_int_Event : LuaDelegate
	{
		public System_Func_Handle_int_Event(LuaFunction func) : base(func) { }
		public System_Func_Handle_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public int Call(Handle param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}

		public int CallWithSelf(Handle param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Func_Handle_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Func<Handle,int> fn = delegate(Handle param0) { return 0; };
			return fn;
		}

		if(!flag)
		{
			System_Func_Handle_int_Event target = new System_Func_Handle_int_Event(func);
			System.Func<Handle,int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Func_Handle_int_Event target = new System_Func_Handle_int_Event(func, self);
			System.Func<Handle,int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Func_Handle_UnityEngine_Vector3_Event : LuaDelegate
	{
		public System_Func_Handle_UnityEngine_Vector3_Event(LuaFunction func) : base(func) { }
		public System_Func_Handle_UnityEngine_Vector3_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public UnityEngine.Vector3 Call(Handle param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			UnityEngine.Vector3 ret = func.CheckVector3();
			func.EndPCall();
			return ret;
		}

		public UnityEngine.Vector3 CallWithSelf(Handle param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			UnityEngine.Vector3 ret = func.CheckVector3();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Func_Handle_UnityEngine_Vector3(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Func<Handle,UnityEngine.Vector3> fn = delegate(Handle param0) { return default(UnityEngine.Vector3); };
			return fn;
		}

		if(!flag)
		{
			System_Func_Handle_UnityEngine_Vector3_Event target = new System_Func_Handle_UnityEngine_Vector3_Event(func);
			System.Func<Handle,UnityEngine.Vector3> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Func_Handle_UnityEngine_Vector3_Event target = new System_Func_Handle_UnityEngine_Vector3_Event(func, self);
			System.Func<Handle,UnityEngine.Vector3> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Func_Handle_UnityEngine_Color_Event : LuaDelegate
	{
		public System_Func_Handle_UnityEngine_Color_Event(LuaFunction func) : base(func) { }
		public System_Func_Handle_UnityEngine_Color_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public UnityEngine.Color Call(Handle param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			UnityEngine.Color ret = func.CheckColor();
			func.EndPCall();
			return ret;
		}

		public UnityEngine.Color CallWithSelf(Handle param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			UnityEngine.Color ret = func.CheckColor();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Func_Handle_UnityEngine_Color(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Func<Handle,UnityEngine.Color> fn = delegate(Handle param0) { return default(UnityEngine.Color); };
			return fn;
		}

		if(!flag)
		{
			System_Func_Handle_UnityEngine_Color_Event target = new System_Func_Handle_UnityEngine_Color_Event(func);
			System.Func<Handle,UnityEngine.Color> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Func_Handle_UnityEngine_Color_Event target = new System_Func_Handle_UnityEngine_Color_Event(func, self);
			System.Func<Handle,UnityEngine.Color> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Func_bool_Event : LuaDelegate
	{
		public System_Func_bool_Event(LuaFunction func) : base(func) { }
		public System_Func_bool_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public bool Call()
		{
			func.BeginPCall();
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}

		public bool CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Func_bool(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Func<bool> fn = delegate() { return false; };
			return fn;
		}

		if(!flag)
		{
			System_Func_bool_Event target = new System_Func_bool_Event(func);
			System.Func<bool> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Func_bool_Event target = new System_Func_bool_Event(func, self);
			System.Func<bool> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_StateGroup_int_Event : LuaDelegate
	{
		public System_Action_StateGroup_int_Event(LuaFunction func) : base(func) { }
		public System_Action_StateGroup_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(StateGroup param0, int param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(StateGroup param0, int param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_StateGroup_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<StateGroup,int> fn = delegate(StateGroup param0, int param1) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_StateGroup_int_Event target = new System_Action_StateGroup_int_Event(func);
			System.Action<StateGroup,int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_StateGroup_int_Event target = new System_Action_StateGroup_int_Event(func, self);
			System.Action<StateGroup,int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_StateHandle_int_Event : LuaDelegate
	{
		public System_Action_StateHandle_int_Event(LuaFunction func) : base(func) { }
		public System_Action_StateHandle_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(StateHandle param0, int param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(StateHandle param0, int param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_StateHandle_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<StateHandle,int> fn = delegate(StateHandle param0, int param1) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_StateHandle_int_Event target = new System_Action_StateHandle_int_Event(func);
			System.Action<StateHandle,int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_StateHandle_int_Event target = new System_Action_StateHandle_int_Event(func, self);
			System.Action<StateHandle,int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_Handle_Event : LuaDelegate
	{
		public System_Action_Handle_Event(LuaFunction func) : base(func) { }
		public System_Action_Handle_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(Handle param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(Handle param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_Handle(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<Handle> fn = delegate(Handle param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_Handle_Event target = new System_Action_Handle_Event(func);
			System.Action<Handle> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_Handle_Event target = new System_Action_Handle_Event(func, self);
			System.Action<Handle> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_StateHandle_Event : LuaDelegate
	{
		public System_Action_StateHandle_Event(LuaFunction func) : base(func) { }
		public System_Action_StateHandle_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(StateHandle param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(StateHandle param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_StateHandle(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<StateHandle> fn = delegate(StateHandle param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_StateHandle_Event target = new System_Action_StateHandle_Event(func);
			System.Action<StateHandle> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_StateHandle_Event target = new System_Action_StateHandle_Event(func, self);
			System.Action<StateHandle> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_LuaInterface_LuaTable_Event : LuaDelegate
	{
		public System_Action_LuaInterface_LuaTable_Event(LuaFunction func) : base(func) { }
		public System_Action_LuaInterface_LuaTable_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(LuaInterface.LuaTable param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(LuaInterface.LuaTable param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_LuaInterface_LuaTable(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<LuaInterface.LuaTable> fn = delegate(LuaInterface.LuaTable param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_LuaInterface_LuaTable_Event target = new System_Action_LuaInterface_LuaTable_Event(func);
			System.Action<LuaInterface.LuaTable> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_LuaInterface_LuaTable_Event target = new System_Action_LuaInterface_LuaTable_Event(func, self);
			System.Action<LuaInterface.LuaTable> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_LuaInterface_LuaTable_StateHandle_Event : LuaDelegate
	{
		public System_Action_LuaInterface_LuaTable_StateHandle_Event(LuaFunction func) : base(func) { }
		public System_Action_LuaInterface_LuaTable_StateHandle_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(LuaInterface.LuaTable param0, StateHandle param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(LuaInterface.LuaTable param0, StateHandle param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_LuaInterface_LuaTable_StateHandle(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<LuaInterface.LuaTable,StateHandle> fn = delegate(LuaInterface.LuaTable param0, StateHandle param1) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_LuaInterface_LuaTable_StateHandle_Event target = new System_Action_LuaInterface_LuaTable_StateHandle_Event(func);
			System.Action<LuaInterface.LuaTable,StateHandle> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_LuaInterface_LuaTable_StateHandle_Event target = new System_Action_LuaInterface_LuaTable_StateHandle_Event(func, self);
			System.Action<LuaInterface.LuaTable,StateHandle> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_LuaInterface_LuaTable_StateHandle_int_Event : LuaDelegate
	{
		public System_Action_LuaInterface_LuaTable_StateHandle_int_Event(LuaFunction func) : base(func) { }
		public System_Action_LuaInterface_LuaTable_StateHandle_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(LuaInterface.LuaTable param0, StateHandle param1, int param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(LuaInterface.LuaTable param0, StateHandle param1, int param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_LuaInterface_LuaTable_StateHandle_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<LuaInterface.LuaTable,StateHandle,int> fn = delegate(LuaInterface.LuaTable param0, StateHandle param1, int param2) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_LuaInterface_LuaTable_StateHandle_int_Event target = new System_Action_LuaInterface_LuaTable_StateHandle_int_Event(func);
			System.Action<LuaInterface.LuaTable,StateHandle,int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_LuaInterface_LuaTable_StateHandle_int_Event target = new System_Action_LuaInterface_LuaTable_StateHandle_int_Event(func, self);
			System.Action<LuaInterface.LuaTable,StateHandle,int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_LuaInterface_LuaTable_UnityEngine_EventSystems_PointerEventData_Event : LuaDelegate
	{
		public System_Action_LuaInterface_LuaTable_UnityEngine_EventSystems_PointerEventData_Event(LuaFunction func) : base(func) { }
		public System_Action_LuaInterface_LuaTable_UnityEngine_EventSystems_PointerEventData_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(LuaInterface.LuaTable param0, UnityEngine.EventSystems.PointerEventData param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PushObject(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(LuaInterface.LuaTable param0, UnityEngine.EventSystems.PointerEventData param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PushObject(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_LuaInterface_LuaTable_UnityEngine_EventSystems_PointerEventData(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<LuaInterface.LuaTable,UnityEngine.EventSystems.PointerEventData> fn = delegate(LuaInterface.LuaTable param0, UnityEngine.EventSystems.PointerEventData param1) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_LuaInterface_LuaTable_UnityEngine_EventSystems_PointerEventData_Event target = new System_Action_LuaInterface_LuaTable_UnityEngine_EventSystems_PointerEventData_Event(func);
			System.Action<LuaInterface.LuaTable,UnityEngine.EventSystems.PointerEventData> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_LuaInterface_LuaTable_UnityEngine_EventSystems_PointerEventData_Event target = new System_Action_LuaInterface_LuaTable_UnityEngine_EventSystems_PointerEventData_Event(func, self);
			System.Action<LuaInterface.LuaTable,UnityEngine.EventSystems.PointerEventData> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class CenterOnChild_OnCenterHandler_Event : LuaDelegate
	{
		public CenterOnChild_OnCenterHandler_Event(LuaFunction func) : base(func) { }
		public CenterOnChild_OnCenterHandler_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.GameObject param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.GameObject param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate CenterOnChild_OnCenterHandler(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			CenterOnChild.OnCenterHandler fn = delegate(UnityEngine.GameObject param0) { };
			return fn;
		}

		if(!flag)
		{
			CenterOnChild_OnCenterHandler_Event target = new CenterOnChild_OnCenterHandler_Event(func);
			CenterOnChild.OnCenterHandler d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			CenterOnChild_OnCenterHandler_Event target = new CenterOnChild_OnCenterHandler_Event(func, self);
			CenterOnChild.OnCenterHandler d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

}

